name: Pre-release version

on:
  push:
    tags:
      - v[0-9][0-9.]+-[a-zA-Z]+[0-9][0-9]?

jobs:
  pre-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create pre-release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$GITHUB_REF_NAME" --notes-from-tag --pre-release
