name: Publish to maven repository

on:
  workflow_call:
    inputs:
      github-packages:
        type: boolean
        default: true
      sonatype:
        type: boolean
        default: true
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_PASSWORD:
        required: true
      GPG_SIGNING_PASSWORD:
        required: true
      GPG_SECRET_KEY:
        required: true

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    env:
      USERNAME: ${{ github.actor }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      IS_MAIN_HOST: ${{ matrix.os == ubuntu-latest }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java '8'
        uses: actions/setup-java@3.13.0
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'

      - name: Publish to repos
        if: ${{ inputs.github-packages || inputs.sonatype }}
        env:
          TASK: ${{ (inputs.github-packages && inputs.sonatype) && 'publish' || (inputs.github-packages && 'publishAllPublicationsToGitHubPackagesRepository' || 'publishAllPublicationsToSonatypeStagingRepository') }}
        run: ./gradlew "$TASK"

