name: Release version

on:
  push:
    tags:
      - v[0-9]*

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$GITHUB_REF_NAME" --notes-from-tag

  publish:
    permissions:
      packages: write
      contents: read

    uses: ./.github/workflows/publish-maven.yml
    secrets: inherit
